### ISSUE TITLE
RC2 >> v1.0

### ISSUE THREAD

**Issue by roklenardic** [djanosik/Moon.OData#1]
Any plans to update to v1.0. Currently the master code fails to build:
Errors in C:\tmp\Moon.OData\src\Moon.AspNetCore.OData\project.json    C:\Users\Rok.SPICA\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
    C:\ProgramData\nuget\Config\nuget-postsharp.config

    Package Microsoft.AspNetCore.Mvc.Core 1.0.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Microsoft.AspNetCore.Mvc.Core 1.0.0 supports:
Feeds used:
      - net451 (.NETFramework,Version=v4.5.1)
    https://api.nuget.org/v3/index.json
      - netstandard1.6 (.NETStandard,Version=v1.6)
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    One or more packages are incompatible with .NETStandard,Version=v1.5.
    https://www.postsharp.net/nuget/packages

Errors in C:\tmp\Moon.OData\samples\Moon.AspNetCore.OData.Sample\project.json
    Package Microsoft.AspNetCore.Mvc 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    Package Microsoft.AspNetCore.Mvc.Core 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc.Core 1.0.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Thanks

**Comment by djanosik** [comment]
I've found xBehave tests are not compatible with xUnit 2.2.0. It will take some time to remove xBehave from solution...

**Comment by djanosik** [comment]
Version 2.2.1+ should be compatible with ASP.NET Core 1.0 RTM.
