### ISSUE TITLE
Filter with 'contains... or contains...' doesn't work correctly

### ISSUE THREAD

**Issue by talismax** [djanosik/Moon.OData#1]
Not sure if you're looking for feedback on this. 

Filter looks like this: ` $filter=contains(Name, 'Fred') or contains(ParentName, 'Fred') `

I think the SQL for this filter doesn't work properly. It basically generates
`WHERE [Name] like '%' + p0 + '%'` and ignores the rest

I thought it was maybe because there's only one unique argument. But even 2 arguments results in the same thing. I think the options object has it correct. It's later when it builds the Where clause that it goes wrong.

**Comment by djanosik** [comment]
Thank you! Binary operators wasn't handled properly in case of method calls. It's probably fixed in https://github.com/djanosik/Moon.OData/commit/504dcc1d88a5fe83e657a9431ab6cbcaa2ac4284 but I need to write more tests.

**Comment by talismax** [comment]
That fixed it. Thanks very much.
