### ISSUE TITLE
Latest published Nuget package is missing some recent commits

### ISSUE THREAD

**Issue by ntanveer** [djanosik/Moon.OData#6]
Hi
I dont think that this commit made it into the most recent package 
https://github.com/djanosik/Moon.OData/commit/504dcc1d88a5fe83e657a9431ab6cbcaa2ac4284

**Comment by djanosik** [comment]
You are right, it didn't. I will release it soon.

**Comment by tjrobinson** [comment]
@djanosik The nuget package hasn't been updated yet. Could this issue be left open until it has?

**Comment by djanosik** [comment]
I've released version 3.1.5.
